3-12 make "01 - Building Blocks" sucssed and remove on push trigger

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,7 +1,6 @@
 name: 01 - Building Blocks
-on:
-  - push
-  - workflow_dispatch
+
+on: workflow_dispatch
 
 jobs:
   echo-hello:
@@ -13,9 +12,13 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Failed step
+      # - name: Failed step
+      #   run: |
+      #     echo "I will fail"
+      #     exit 1
+      - name: Successful step
         run: |
-          echo "I will fail"
-          exit 1
+          echo "I will succeed"
+          exit 0
       - name: Say goodbye
         run: echo "Goodbye!"
