11-42 fix#1

diff --git a/.github/workflows/10-execution-flow.yaml b/.github/workflows/10-execution-flow.yaml
--- a/.github/workflows/10-execution-flow.yaml
+++ b/.github/workflows/10-execution-flow.yaml
@@ -21,8 +21,10 @@ jobs:
       - name: Unit tests
         run: echo "Running tests..."
       - name: Failing tests
-        if: ${{ github.event.inputs.pass-unit-tests == false }}
-        run: echo "Failing tests..." && exit 1
+        if: ${{ inputs.pass-unit-tests == false }}
+        run: |
+          echo "Failing tests..."
+          exit 1
   deploy-nonprod:
     runs-on: ubuntu-latest
     needs: [lint-build, unit-tests]
