15-68 new(16 - Working with Environments) workflow added

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -23,14 +23,14 @@ jobs:
         uses: actions/setup-node@v6
         with:
           node-version: ${{ matrix.node-version }}
-      - name: Fail if experimental
-        if: ${{ matrix.tag == 'experimental' }}
-        run: |
-          echo "This is an experimental build"
-          exit 1
+      # - name: Fail if experimental  # uncomment to experiment
+      #   if: ${{ matrix.tag == 'experimental' }}
+      #   run: |
+      #     echo "This is an experimental build"
+      #     exit 1
       - name: Perform some tests
         run: |
-          sleep 10
+          # sleep 10
           echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
       - name: Upload test results
         run: |
@@ -56,9 +56,9 @@ jobs:
             shape: circle
             size: medium
             opacity: 70
-        exclude:
+        exclude:  # is being processed before include options
           # - opacity: 75 # leads to the "Matrix exclude key 'opacity' does not match any key within the matrix" error
-          - color: green
+          - color: green  # doesn't affect new combinations added in include
             shape: circle
     steps:
       - name: Dummy step
